var all_items = [
{name: "Alloy Bracelet",silver: 800,time: "15h",building: "Warehouse",upgrade: "Crates",quality: "Rare",
resource:[{name: "Gold Bracelet",qty: 2,qual: "uncommon",z:null},{name: "Lead",qty: 8,qual: "uncommon",z:null},{name: "Precious Ore",qty: 6,qual: "uncommon",z:null}]},
{name: "Alloy Chain",silver: 800,time: "15h",building: "Market",upgrade: "Ore Stall",
resource:[{name: "Silver Chain",qty: 5,z:null},{name: "Lead",qty: 10,qual: "Uncommon",z:null},{name: "Precious Ore",qty: 10,qual: "Uncommon",z:null}]},
{name: "Alloy Necklace",silver: 800,time: "15h",building: "Warehouse",upgrade: "Cargo Wagons",quality: "Rare",
resource:[{name: "Gold Necklace",qty: 2,qual: "uncommon",z:null},{name: "Lead",qty: 8,qual: "uncommon",z:null},{name: "Precious Ore",qty: 6,qual: "uncommon",z:null}]},
{name: "Alloy Pendant",silver: 800,time: "15h",building: "Market",upgrade: "Ore Stall",quality: "Rare",
resource:[{name: "Gold Necklace",qty: 2,qual: "Uncommon",z:null},{name: "Precious Ore",qty: 9,qual: "Uncommon",z:null},{name: "Lead",qty: 5,qual: "Uncommon",z:null}]},
{name: "Alloyed Torc",silver: 2500,time: "1d 4h",building: "Mine",upgrade: "Molds",quality: "Legendary",
resource:[{name: "Moonstone Torc",qty: 3,qual: "Rare",z:null},{name: "Precious Ore",qty: 20,qual: "Uncommon",z:null},{name: "Lead",qty: 10,qual: "Uncommon",z:null}]},
{name: "Apprentice Pyromancer",silver: 5000,time: "15h",building: "Alchemists' Guild",upgrade: "Apprentice",quality: "Legendary",type: "Unit",
resource:[{name: "Ceremonial Bowl",qty: 5,qual: "Uncommon",z:null},{name: "Wildfire",qty: 3,qual: "Rare",z:null},{name: "Dyed Textile",qty: 12,qual: "Uncommon",z:null}]},
{name: "Arakh",silver: 450,time: "12h",building: "Reliquary",upgrade: "Dragon Claws",
resource:[{name: "Broadsword",qty: 1,qual: "Uncommon",z:null},{name: "Axe",qty: 1,qual: "Uncommon",z:null},{name: "Longsword",qty: 2,z:null}]},
{name: "Arbor Gold",silver: 75,time: "4h",building: "Arbor",
resource:[{name: "Mead",qty: 3,z:null},{name: "Grains",qty: 15,z:null}]},
{name: "Archer",silver: 200,time: "6h",building: "Practice Yard",upgrade: "Target Range",
resource:[{name: "Composite Bow",qty: 2,qual: "Uncommon",z:null},{name: "Militia",qty: 2,z:null},{name: "Bowman",qty: 2,qual: "Uncommon",pic: "Archer.jpg",z:null}]},
{name: "Armored Knight",silver: 450,time: "12h",building: "Tourney Arena",
resource:[{name: "Foot Soldier",qty: 1,qual: "Uncommon",z:null},{name: "Breastplate",qty: 1,qual: "Uncommon",z:null},{name: "Barred Helm",qty: 1,qual: "Uncommon|resource1_pic = Armored Row.jpg",z:null}]},
{name: "Assassin",silver: 450,time: "12h",building: "Watchtower",upgrade: "Archery Platforms",
resource:[{name: "Thief",qty: 1,pic: "Hooded Figure.jpg",z:null},{name: "Heavy Crossbow",qty: 1,qual: "Uncommon",z:null},{name: "Guard's Uniform",qty: 1,qual: "Uncommon",z:null}]},
{name: "Asshai Book",silver: 200,time: "6h",building: "R'hllor Temple",upgrade: "Asshai Prophecy Books",
resource:[{name: "Leather-bound Book",qty: 1,z:null},{name: "Milk of the Poppy",qty: 1,z:null},{name: "Longsword",qty: 1,z:null}]},
{name: "Aurochs",silver: 800,time: "15h",building: "Feast",upgrade: "Flagons of Drink",quality: "Rare",
resource:[{name: "Grains",qty: 18,z:null},{name: "Pure Water",qty: 3,z:null},{name: "Horse",qty: 12,z:null}]},
{name: "Axe",silver: 200,time: "6h",building: "Smithy",upgrade: "Armor Rack",
resource:[{name: "Dagger",qty: 2,z:null},{name: "Iron",qty: 3,z:null},{name: "Wood",qty: 3,z:null}]},
{name: "Chance of Baby Dragon",silver: 5000,time: "1d 12h",building: "Reliquary",upgrade: "Dragon Skull",quality: "Peerless",pic: "Baby Dragon.jpg",special: "Very small chance of hatching a baby dragon",
resource:[{name: "Dragon Egg",qty: 1,qual: "peerless",pic: "Live Dragon Egg.jpg",z:null},{name: "Pyre",qty: 5,qual: "rare",z:null},{name: "Dragon Horn",qty: 1,qual: "Legendary",z:null}]},
{name: "Chance of Baby Green Dragon",silver: 10000,time: "18h",building: "Alchemists' Guild",upgrade: "Fresh Wildfire",quality: "Peerless",special: "Small chance of evolving a Baby Green Dragon",
resource:[{name: "Baby Dragon",qty: 1,qual: "peerless",pic: "Baby_Dragon.jpg",z:null},{name: "Apprentice Pyromancer",qty: 1,qual: "Legendary",pic: "Apprentice Pyromancer.jpg",z:null},{name: "Weirwood",qty: 7,qual: "Rare",z:null}]},
{name: "Chance of Baby Red Dragon",silver: 10000,time: "18h",building: "Alchemists' Guild",upgrade: "Fresh Wildfire",quality: "Peerless",special: "Small chance of evolving a Baby Red Dragon",
resource:[{name: "Baby Dragon",qty: 1,qual: "Peerless",z:null},{name: "Apprentice Pyromancer",qty: 1,qual: "Legendary",pic: "Apprentice Pyromancer.jpg",z:null},{name: "Sacrifice",qty: 7,qual: "Rare",z:null}]},
{name: "Chance of Baby Tan Dragon",silver: 10000,time: "18h",building: "Alchemists' Guild",upgrade: "Fresh Wildfire",quality: "Peerless",special: "Small chance of evolving a Baby Tan Dragon",
resource:[{name: "Baby Dragon",qty: 1,qual: "peerless",pic: "Baby_Dragon.jpg",z:null},{name: "Apprentice Pyromancer",qty: 1,qual: "Legendary",pic: "Apprentice Pyromancer.jpg",z:null},{name: "Valyrian Glyphs",qty: 7,qual: "Rare",z:null}]},
{name: "Barred Helm",silver: 200,time: "6h",building: "Practice Yard",quality: "Uncommon",type: "Body",
resource:[{name: "Halfhelm",qty: 2,z:null},{name: "Fur",qty: 5,z:null},{name: "Wood",qty: 1,z:null}]},
{name: "Bascinet",silver: 2500,time: "1d 4h",building: "Arbor",upgrade: "Barrels",quality: "Legendary",
resource:[{name: "Greathelm",qty: 3,qual: "Rare",z:null},{name: "Lead",qty: 15,qual: "Uncommon",z:null},{name: "Steel",qty: 15,qual: "Uncommon",z:null}]},
{name: "Bill of Sale",silver: 200,time: "6h",building: "Treasury",upgrade: "Crown and Scepter",
resource:[{name: "Coinage",qty: 1,z:null},{name: "Leather-bound Book",qty: 1,z:null},{name: "Cloth",qty: 6,z:null}]},
{name: "Binding Contract",silver: 20000,time: "12h",building: "Reliquary",upgrade: "Dragon Skull",
resource:[{name: "Deposit",qty: 1,qual: "Legendary",z:null},{name: "Secure Lockbox",qty: 2,qual: "rare",z:null},{name: "False Coin",qty: 4,qual: "Legendary",pic: "Braavosi Coin.jpg",z:null}]},
{name: "Black Bear Skull Helm",silver: 750,time: "3h",building: "Godswood",quality: "Uncommon",type: "Body",
resource:[{name: "Brown Bear Skull Helm",qty: 1,qual: "common",pic: "Bear Skull Helm.jpg",z:null},{name: "Merchant's Boots",qty: 2,pic: "Boots.jpg",z:null},{name: "Stone",qty: 8,z:null}]},
{name: "Black Diamond Ring",silver: 450,time: "12h",building: "Arbor",upgrade: "Pergola",quality: "Rare",
resource:[{name: "Gold Ring",qty: 5,z:null},{name: "Leather-bound Book",qty: 3,z:null}]},
{name: "Blazing Fire Archer",silver: 2500,time: "1d 4h",building: "Alchemists' Guild",upgrade: "Preparation Cell",quality: "Legendary",
resource:[{name: "Fire Archer",qty: 3,qual: "Rare",z:null},{name: "Flickering Fire",qty: 3,pic: "Pyre.jpg",z:null},{name: "Hard Wood",qty: 12,qual: "Uncommon",z:null}]},
{name: "Blindeye",silver: 200,time: "6h",building: "Workshop",upgrade: "Signal Lantern",
resource:[{name: "Dirk",qty: 1,z:null},{name: "Grains",qty: 8,z:null},{name: "Fish",qty: 4,z:null}]},
{name: "Blue Gem",silver: 15,time: "30m",building: "Stables",type: "Resource",
resource:[{name: "Peddler",qty: 2,pic: "Trader.jpg",z:null},{name: "Ore",qty: 2,z:null},{name: "Stone",qty: 1,z:null}]},
{name: "Bowman",silver: 200,time: "6h",building: "Practice Yard",upgrade: "Bows Quivers and Arrows",
resource:[{name: "Shortbow",qty: 3,pic: "Shortbow.jpg",z:null},{name: "Militia",qty: 3,pic: "Militia.jpg",z:null}]},
{name: "Braavosi Brigantine",silver: 250,time: "3h",building: "Godswood",
resource:[{name: "Braavosi Cog",qty: 1,qual: "common",pic: "Braavosi Brigantine.jpg",z:null},{name: "Dinghy",qty: 2,qual: "Uncommon",pic: "Sailboat.jpg",z:null},{name: "Wood",qty: 8,z:null}]},
{name: "Braavosi Carrack",silver: 5000,time: "12h",building: "Godswood",
resource:[{name: "Braavosi Longship",qty: 1,qual: "legendary",pic: "Braavosi Brigantine.jpg",z:null},{name: "Leather Belt",qty: 6,z:null},{name: "Fine Wood",qty: 6,qual: "Uncommon",z:null}]},
{name: "Braavosi Galleon",silver: 500,time: "6h",building: "Godswood",
resource:[{name: "Braavosi Brigantine",qty: 1,qual: "uncommon",pic: "Braavosi Brigantine.jpg",z:null},{name: "Rope Belt",qty: 4,qual: "Rare",pic: "Woven Belt.jpg",z:null},{name: "Wood",qty: 16,z:null}]},
{name: "Braavosi Longship",silver: 2000,time: "9h",building: "Godswood",
resource:[{name: "Braavosi Galleon",qty: 1,qual: "rare",pic: "Braavosi Brigantine.jpg",z:null},{name: "Rainwood Cloak",qty: 6,qual: "Uncommon",pic: "Satin Cloak.jpg",z:null},{name: "Hard Wood",qty: 4,qual: "Uncommon",z:null}]},
{name: "Braavosi Trade Galleon",silver: 5000,time: "12h",building: "Godswood",
resource:[{name: "Braavosi Longship",qty: 1,qual: "legendary",pic: "Braavosi Brigantine.jpg",z:null},{name: "Cart",qty: 6,pic: "Cart of Tools.jpg",z:null},{name: "Precious Ore",qty: 6,qual: "Uncommon",z:null}]},
{name: "Braavosi Warship",silver: 5000,time: "12h",building: "Godswood",
resource:[{name: "Braavosi Longship",qty: 1,qual: "legendary",pic: "Braavosi Brigantine.jpg",z:null},{name: "Shortbow",qty: 6,z:null},{name: "Lead",qty: 6,qual: "Uncommon",z:null}]},
{name: "Bravo's Blade",silver: 750,time: "3h",building: "Godswood",quality: "Uncommon",type: "Hand",
resource:[{name: "Braavosi Blade",qty: 1,qual: "Common",pic: "Bravos_Blade.jpg",z:null},{name: "Biting Blade",qty: 2,qual: "Uncommon",z:null},{name: "Iron",qty: 8,qual: "Common",z:null}]},
{name: "Breastplate",silver: 200,time: "6h",building: "Armory",upgrade: "Body Armor",quality: "Uncommon",
resource:[{name: "Leather Armor",qty: 2,z:null},{name: "Iron",qty: 4,z:null},{name: "Fur",qty: 2,z:null}]},
{name: "Broadsword",silver: 200,time: "6h",building: "Smithy",upgrade: "Hammer and Tongs",
resource:[{name: "Shortsword",qty: 2,pic: "Short Sword.jpg",z:null},{name: "Iron",qty: 4,z:null},{name: "Wood",qty: 2,z:null}]},
{name: "Caravan",silver: 450,time: "12h",building: "Warehouse",upgrade: "Cargo Wagons",quality: "Rare",
resource:[{name: "Wagon",qty: 3,z:null},{name: "Merchant",qty: 3,z:null},{name: "Grains",qty: 6,z:null}]},
{name: "Cart",silver: 60,time: "3h",building: "Warehouse",upgrade: "Crates",
resource:[{name: "Wood",qty: 5,z:null},{name: "Iron",qty: 1,z:null}]},
{name: "Catapult",silver: 200,time: "6h",building: "Siege Works",upgrade: "Catapult",
resource:[{name: "Trebuchet",qty: 2,z:null},{name: "Stone",qty: 4,z:null},{name: "Grains",qty: 2,z:null}]},
{name: "Cavalry Commander",silver: 20000,time: "12h",building: "Tourney Arena",upgrade: "Herald",
resource:[{name: "Elite Cavalryman",qty: 1,qual: "Legendary",z:null},{name: "Grand Barred Helm",qty: 2,qual: "rare",z:null},{name: "Grand Pack Horse",qty: 4,qual: "Legendary",pic: "Pack Horse.jpg",z:null}]},
{name: "Ceremonial Bowl",silver: 450,time: "12h",building: "Glasshouse",upgrade: "Topiary",
resource:[{name: "Lead",qty: 8,qual: "Uncommon",z:null},{name: "Dyed Textile",qty: 8,qual: "Uncommon",z:null},{name: "Hard Wood",qty: 8,qual: "Uncommon",z:null}]},
{name: "Ceremonial Dagger",silver: 800,time: "15h",building: "Sept",upgrade: "Altar to the Stranger",
resource:[{name: "Oracle",qty: 1,qual: "Rare",pic: "Red Priest.jpg",z:null},{name: "Steel",qty: 5,qual: "Uncommon",z:null},{name: "Precious Ore",qty: 6,qual: "Uncommon",z:null}]},
{name: "Children of the Forest Bow",silver: 1850,time: "24h",building: "Godswood",
resource:[{name: "Dead Weirwood",qty: 10,qual: "Rare",z:null},{name: "Ancient Dragonglass Arrowhead",qty: 1,qual: "Rare",z:null},{name: "Composite Bow",qty: 2,qual: "Uncommon",z:null}]},
{name: "Coinage",silver: 60,time: "3h",building: "Warehouse",
resource:[{name: "Gold Ring",qty: 1,z:null},{name: "Ore",qty: 2,z:null}]},
{name: "Composite Bow",silver: 200,time: "6h",building: "Practice Yard",upgrade: "Archery Butts",
resource:[{name: "Shortbow",qty: 2,z:null},{name: "Wood",qty: 3,z:null},{name: "Cloth",qty: 3,z:null}]},
{name: "Courtesan",silver: 450,time: "12h",building: "Shanty",upgrade: "Pit Fires",
resource:[{name: "Thief",qty: 1,pic: "Hooded Figure.jpg",z:null},{name: "Moleskin Gloves",qty: 1,qual: "Uncommon",z:null},{name: "Woven Belt",qty: 1,qual: "Uncommon",z:null}]},
{name: "Courtier's Outfit",silver: 450,time: "12h",building: "Glasshouse",upgrade: "Reflecting Pool",
resource:[{name: "Guard's Uniform",qty: 2,qual: "Uncommon",z:null},{name: "Fur",qty: 9,z:null},{name: "Ore",qty: 7,z:null}]},
{name: "Crossbowman",silver: 200,time: "6h",building: "Watchtower",upgrade: "Watchmen",
resource:[{name: "Militia",qty: 3,z:null},{name: "Light Crossbow",qty: 3,z:null}]},
{name: "Cuirass",silver: 450,time: "12h",building: "Hunting Lodge",upgrade: "Supply Shed",
resource:[{name: "Breastplate",qty: 2,qual: "Uncommon",z:null},{name: "Iron",qty: 12,pic: "Iron.jpg",z:null},{name: "Fur",qty: 2,z:null}]},
{name: "Dagger",silver: 60,time: "3h",building: "Smithy",
resource:[{name: "Wood",qty: 3,z:null},{name: "Iron",qty: 2,z:null},{name: "Cloth",qty: 1,z:null}]},
{name: "Dark Diamond Ring",silver: 800,time: "15h",building: "Treasury",upgrade: "Gold Armor",
resource:[{name: "Gold Ring",qty: 6,z:null},{name: "Precious Ore",qty: 10,qual: "Uncommon",z:null},{name: "Steel",qty: 4,qual: "Uncommon",z:null}]},
{name: "Deadly Poison",silver: 20000,time: "12h",building: "Arbor",upgrade: "Flasks",
resource:[{name: "Undetectable Poison",qty: 1,qual: "Legendary",pic: "Poisoned Cask Deluxe.jpg",z:null},{name: "Widow's Blood",qty: 2,qual: "rare",pic: "Dreamwine.jpg",z:null},{name: "intent Scholar",qty: 4,qual: "Legendary",pic: "Hooded Figure.jpg",z:null}]},
{name: "Decorative Blade",silver: 10,time: "30s",building: "Smithy",
resource:[{name: "Iron",qty: 1,z:null},{name: "Wood",qty: 1,z:null},{name: "Ore",qty: 2,z:null}]},
{name: "Delicate Satin Cloak",silver: 800,time: "15h",building: "Workshop",upgrade: "Suspicious Cart",
resource:[{name: "Satin Cloak",qty: 2,qual: "Uncommon",z:null},{name: "Dyed Textile",qty: 10,qual: "Uncommon",z:null},{name: "Lead",qty: 4,qual: "Uncommon",z:null}]},
{name: "Delicate Silk Garment",silver: 800,time: "14h 0m",building: "Embassy",upgrade: "Balcony",
resource:[{name: "Silk Garment",qty: 2,qual: "Uncommon",z:null},{name: "Dyed Textile",qty: 10,qual: "Uncommon",z:null},{name: "Precious Ore",qty: 4,qual: "Uncommon",z:null}]},
{name: "Deposit",silver: 2500,time: "1d 4h",building: "Reliquary",upgrade: "Dragon Skull",quality: "Legendary",
resource:[{name: "Receipt",qty: 3,qual: "Rare",z:null},{name: "Dyed Textile",qty: 15,qual: "Uncommon",z:null},{name: "Fine Wood",qty: 15,qual: "Uncommon",z:null}]},
{name: "Devout",silver: 60,time: "3h",building: "Sept",
resource:[{name: "Smallfolk",qty: 1,z:null},{name: "Fish",qty: 5,z:null},{name: "Linen Clothing",qty: 1,z:null}]},
{name: "Direwolf Matriarch Skull Helm",silver: 6000,time: "12h",building: "Godswood",quality: "Peerless",type: "Body",
resource:[{name: "Direwolf Skull Helm",qty: 1,qual: "legendary",pic: "Direwolf Skull Helm.jpg",z:null},{name: "Northern Fur",qty: 8,qual: "rare",z:null},{name: "Glacial Water",qty: 3,qual: "rare",z:null}]},
{name: "Direwolf Patriarch Skull Helm",silver: 6000,time: "12h",building: "Godswood",quality: "Peerless",type: "Body",
resource:[{name: "Direwolf Skull Helm",qty: 1,qual: "legendary",pic: "Direwolf Skull Helm.jpg",z:null},{name: "Northern Horse",qty: 8,qual: "rare",z:null},{name: "Glacial Water",qty: 3,qual: "rare",z:null}]},
{name: "Direwolf Skull Helm",silver: 3000,time: "9h",building: "Godswood",quality: "Legendary",type: "Body",
resource:[{name: "Snow Bear Skull Helm",qty: 1,qual: "rare",pic: "Bear Skull Helm.jpg",z:null},{name: "Sanded Bow",qty: 6,qual: "uncommon",pic: "Composite Bow.jpg",z:null},{name: "Hard Wood",qty: 4,qual: "uncommon",z:null}]},
{name: "Dirk",silver: 60,time: "3h",building: "Workshop",
resource:[{name: "Iron",qty: 2,z:null},{name: "Wood",qty: 3,z:null},{name: "Cloth",qty: 1,z:null}]},
{name: "Doublet",silver: 60,time: "3h",building: "Holdfast",
resource:[{name: "Cloth",qty: 2,z:null},{name: "Fur",qty: 2,z:null}]},
{name: "Dragon Egg",silver: 5000,time: "1d 12h",building: "Alchemists' Guild",upgrade: "Fresh Wildfire",
resource:[{name: "Dormant Dragon Egg",qty: 1,qual: "Peerless",z:null},{name: "Offering",qty: 1,qual: "Legendary",z:null},{name: "Incense",qty: 7,qual: "Uncommon",z:null}]},
{name: "Dragon Horn",silver: 2500,time: "1d 4h",building: "Shipyard",upgrade: "Dry Dock",quality: "Legendary",
resource:[{name: "Great Horn",qty: 1,qual: "Legendary",z:null},{name: "Valyrian Glyphs",qty: 10,qual: "Rare",z:null},{name: "Jeweled Armor",qty: 1,qual: "Legendary",z:null}]},
{name: "Dreamwine",silver: 200,time: "6h",building: "Embassy",upgrade: "Fortified Gate",
resource:[{name: "Milk of the Poppy",qty: 1,z:null},{name: "Grains",qty: 8,z:null},{name: "Fish",qty: 4,z:null}]},
{name: "Eavesdropper",silver: 60,time: "3h",building: "Embassy",
resource:[{name: "Smallfolk",qty: 1,z:null}]},
{name: "Elite Cavalryman",silver: 2500,time: "1d 4h",building: "Tourney Arena",upgrade: "Herald",quality: "Legendary",type: "Unit",special: "+6% to all attacks and defense",
resource:[{name: "Heavy Knight",qty: 1,qual: "Rare",pic: "Lancer.jpg",z:null},{name: "Steel-Shod Warhorse",qty: 1,qual: "Rare",pic: "Destrier Deluxe.jpg",z:null},{name: "Masterwork Greatsword",qty: 1,qual: "Legendary",z:null}]},
{name: "Elite Phalanx",silver: 2500,time: "1d 4h",building: "Armory",upgrade: "Tower Shields",quality: "Legendary",
resource:[{name: "Phalanx",qty: 2,qual: "Rare",z:null},{name: "Steel",qty: 20,qual: "Uncommon",z:null},{name: "Hard Wood",qty: 10,qual: "Uncommon",z:null}]},
{name: "Elite Reaving Ship",silver: 2400,time: "1d 4h",building: "Shipyard",upgrade: "Slip",
resource:[{name: "Reaving Ship",qty: 3,qual: "Rare",z:null},{name: "Steel",qty: 17,qual: "Uncommon",z:null},{name: "Lead",qty: 13,qual: "Uncommon",z:null}]},
{name: "Embroidered Tunic",silver: 450,time: "12h",building: "Reliquary",upgrade: "Dragon Bones",quality: "Rare",
resource:[{name: "Silk Garment",qty: 2,qual: "Uncommon",z:null},{name: "Cloth",qty: 9,z:null},{name: "Ore",qty: 5,z:null}]},
{name: "Emissary",silver: 200,time: "6h",building: "Embassy",upgrade: "Guest House",
resource:[{name: "Eavesdropper",qty: 1,pic: "Hooded Figure.jpg",z:null},{name: "Silk Garment",qty: 2,qual: "Uncommon",z:null},{name: "Fur",qty: 3,z:null}]},
{name: "Expert Crossbowman",silver: 800,time: "15h",building: "Watchtower",upgrade: "Third Story",quality: "Rare",
resource:[{name: "Crossbowman",qty: 1,qual: "Uncommon",z:null},{name: "Heavy Crossbow",qty: 1,qual: "Uncommon",z:null},{name: "Hard Wood",qty: 14,qual: "Uncommon",z:null}]},
{name: "Extravagant Necklace",silver: 20000,time: "12h",building: "Fishery",upgrade: "Poles",
resource:[{name: "Heirloom Necklace",qty: 1,qual: "Legendary",z:null},{name: "Alloy Necklace",qty: 2,qual: "rare",z:null},{name: "Grand Pewter Collar",qty: 4,qual: "Legendary",pic: "Silver Torc.jpg",z:null}]},
{name: "Extravagant Torc",silver: 20000,time: "12h",building: "Mine",upgrade: "Molds",
resource:[{name: "Alloyed Torc",qty: 1,qual: "Legendary",z:null},{name: "Alloy Pendant",qty: 2,qual: "rare",z:null},{name: "Polished Antique Gold Necklace",qty: 4,qual: "Legendary",pic: "Gold Necklace.jpg",z:null}]},
{name: "Faceless Assassin Blade",silver: 6000,time: "12h",building: "Godswood",
resource:[{name: "Faceless Man Blade",qty: 1,qual: "legendary",pic: "Faceless Blade.jpg",z:null},{name: "Fingerless Gloves",qty: 6,z:null},{name: "Dyed Textile",qty: 6,qual: "Uncommon",z:null}]},
{name: "Faceless Deceiver Blade",silver: 6000,time: "12h",building: "Godswood",
resource:[{name: "Faceless Man Blade",qty: 1,qual: "legendary",pic: "Faceless Blade.jpg",z:null},{name: "Cart",qty: 6,pic: "Cart of Tools.jpg",z:null},{name: "Fine Wood",qty: 6,qual: "Uncommon",z:null}]},
{name: "Faceless Killer Blade",silver: 6000,time: "12h",building: "Godswood",
resource:[{name: "Faceless Man Blade",qty: 1,qual: "legendary",pic: "Faceless Blade.jpg",z:null},{name: "Halfhelm",qty: 6,z:null},{name: "Lead",qty: 6,qual: "Uncommon",z:null}]},
{name: "Faceless Man Blade",silver: 3000,time: "9h",building: "Godswood",
resource:[{name: "Water Dancer Blade",qty: 1,qual: "rare",pic: "Bravos Blade.jpg",z:null},{name: "Poisoned Blade",qty: 6,qual: "Uncommon",pic: "Longsword.jpg",z:null},{name: "Steel",qty: 4,qual: "Uncommon",z:null}]},
{name: "Feral Direwolf Skull Helm",silver: 6000,time: "12h",building: "Godswood",quality: "Peerless",type: "Body",
resource:[{name: "Direwolf Skull Helm",qty: 1,qual: "legendary",pic: "Direwolf Skull Helm.jpg",z:null},{name: "Northern Wood",qty: 8,qual: "rare",z:null},{name: "Glacial Water",qty: 3,qual: "rare",z:null}]},
{name: "Fingerless Gloves",silver: 60,time: "3h",building: "Shanty",
resource:[{name: "Cloth",qty: 3,z:null},{name: "Fur",qty: 3,z:null}]},
{name: "Fire Archer",silver: 450,time: "12h",building: "Alchemists' Guild",upgrade: "Clay Jars",quality: "Rare",type: "Unit",
resource:[{name: "Archer",qty: 1,qual: "Rare",z:null},{name: "Wood",qty: 2,z:null},{name: "Iron",qty: 2,z:null}]},
{name: "Fireship",silver: 2500,time: "1d 4h",building: "Alchemists' Guild",upgrade: "Fresh Wildfire",
resource:[{name: "Wildfire",qty: 8,qual: "Rare",z:null},{name: "Smuggling Vessel",qty: 2,qual: "Rare",z:null},{name: "Fire Archer",qty: 2,qual: "Rare",z:null}]},
{name: "Fisherman",silver: 60,time: "1h",building: "Fishery",quality: "common",
resource:[{name: "Smallfolk",qty: 1,z:null},{name: "Fish",qty: 6,z:null}]},
{name: "Flickering Fire",silver: 60,time: "3h",building: "R'hllor Temple",upgrade: "Braziers",
resource:[{name: "Wood",qty: 3,z:null},{name: "Grains",qty: 2,z:null},{name: "Iron",qty: 1,z:null}]},
{name: "Fool",silver: 60,time: "3h",building: "Feast",
resource:[{name: "Smallfolk",qty: 1,z:null},{name: "Cloth",qty: 3,z:null},{name: "Ore",qty: 2,z:null}]},
{name: "Foot Soldier",silver: 200,time: "6h",building: "Tourney Arena",
resource:[{name: "Smallfolk",qty: 1,z:null},{name: "Longsword",qty: 1,z:null},{name: "Guard's Uniform",qty: 1,qual: "Uncommon",z:null}]},
{name: "Forest Armor",silver: 800,time: "15h",building: "Godswood",upgrade: "Pool",quality: "Rare",
resource:[{name: "Weirwood",qty: 5,qual: "Rare",z:null},{name: "Lead",qty: 10,qual: "Uncommon",z:null},{name: "Breastplate",qty: 2,qual: "Uncommon",z:null}]},
{name: "Fresh-baked Bread",silver: 10,time: "1h",building: "Sept",type: "Food",
resource:[{name: "Fish",qty: 2,z:null},{name: "Grains",qty: 2,z:null},{name: "Wood",qty: 1,z:null}]},
{name: "Fur-trimmed Cloak",silver: 450,time: "12h",building: "Hunting Lodge",upgrade: "Cleaning and Skinning Station",quality: "Rare",
resource:[{name: "Satin Cloak",qty: 2,qual: "Uncommon",z:null},{name: "Fur",qty: 8,z:null},{name: "Cloth",qty: 6,z:null}]},
{name: "Furrier",silver: 450,time: "12h",building: "Artisan Quarters",upgrade: "Jewelry",quality: "Rare",
resource:[{name: "Merchant",qty: 6,z:null},{name: "Fur",qty: 8,z:null},{name: "Ore",qty: 4,z:null}]},
{name: "Gold Bracelet",silver: 200,time: "6h",building: "Treasury",upgrade: "Gold Armor",
resource:[{name: "Silver Bracelet",qty: 1,z:null},{name: "Gold Ring",qty: 1,z:null},{name: "Ore",qty: 6,z:null}]},
{name: "Gold Necklace",silver: 200,time: "6h",building: "Treasury",upgrade: "Gold Armor",
resource:[{name: "Silver Necklace",qty: 1,z:null},{name: "Gold Ring",qty: 1,z:null},{name: "Ore",qty: 6,z:null}]},
{name: "Gold Ring",silver: 60,time: "3h",building: "Market",upgrade: "Ore Stall",
resource:[{name: "Ore",qty: 5,z:null}]},
{name: "Gold Torc",silver: 200,time: "6h",building: "Treasury",upgrade: "Gold Armor",
resource:[{name: "Silver Torc",qty: 1,z:null},{name: "Gold Ring",qty: 1,z:null},{name: "Ore",qty: 6,z:null}]},
{name: "Grand Barred Helm",silver: 800,time: "15h",building: "Tourney Arena",upgrade: "Viewing Box",quality: "Rare",
resource:[{name: "Barred Helm",qty: 2,qual: "Uncommon",z:null},{name: "Steel",qty: 8,qual: "Uncommon",z:null},{name: "Lead",qty: 6,qual: "Uncommon",z:null}]},
{name: "Grand Breastplate",silver: 800,time: "15h",building: "Armory",upgrade: "Body Armor",quality: "Rare",type: "Body",
resource:[{name: "Breastplate",qty: 2,qual: "Rare",link: "Breastplate",z:null},{name: "Steel",qty: 8,qual: "Uncommon",link: "Steel",z:null},{name: "Lead",qty: 6,qual: "Uncommon",link: "Lead",z:null}]},
{name: "Grand Cuirass",silver: 2500,time: "1d 4h",building: "Shipyard",upgrade: "Coils of Rope",quality: "Legendary",
resource:[{name: "Surcoat",qty: 3,qual: "Rare",z:null},{name: "Steel",qty: 20,qual: "Uncommon",z:null},{name: "Dyed Textile",qty: 10,qual: "Uncommon",z:null}]},
{name: "Grand Shield",silver: 800,time: "15h",building: "Holdfast",upgrade: "Portcullis",quality: "Rare",
resource:[{name: "Metal Shield",qty: 2,qual: "Uncommon",pic: "Hefty Shield.jpg",z:null},{name: "Steel",qty: 8,qual: "Uncommon",z:null},{name: "Dyed Textile",qty: 6,qual: "Uncommon",z:null}]},
{name: "Great Horn",silver: 2500,time: "1d 4h",building: "Hunting Lodge",upgrade: "Cleaning and Skinning Station",quality: "Legendary",
resource:[{name: "Aurochs",qty: 2,qual: "Rare",z:null},{name: "Forest Armor",qty: 1,qual: "Rare",z:null},{name: "Crystal Sword",qty: 3,qual: "Legendary",z:null}]},
{name: "Greathelm",silver: 450,time: "12h",building: "Arbor",upgrade: "Barrels",
resource:[{name: "Barred Helm",qty: 2,qual: "Uncommon",z:null},{name: "Iron",qty: 8,z:null},{name: "Fur",qty: 6,z:null}]},
{name: "Guard's Uniform",silver: 200,time: "6h",building: "Watchtower",upgrade: "Watchmen",quality: "uncommon",
resource:[{name: "Unremarkable Tunic",qty: 1,z:null},{name: "Fur",qty: 5,z:null},{name: "Cloth",qty: 7,z:null}]},
{name: "Guard's Uniform",silver: 200,time: "6h",building: "Watchtower",upgrade: "Watchmen",quality: "uncommon",
resource:[{name: "Unremarkable Tunic",qty: 1,z:null},{name: "Fur",qty: 5,z:null},{name: "Cloth",qty: 7,z:null}]},
{name: "Guild Assassin",silver: 2500,time: "1d 4h",building: "Watchtower",upgrade: "Archery Platforms",quality: "Legendary",
resource:[{name: "Assassin",qty: 3,qual: "Rare",z:null},{name: "Dyed Textile",qty: 15,qual: "Uncommon",z:null},{name: "Fine Wood",qty: 15,qual: "Uncommon",z:null}]},
{name: "Halberdier",silver: 450,time: "12h",building: "Glasshouse",upgrade: "Orangery",
resource:[{name: "Militia",qty: 1,z:null},{name: "Spear",qty: 1,qual: "Rare",z:null},{name: "Fur",qty: 3,z:null}]},
{name: "Halfhelm",silver: 60,time: "3h",building: "Practice Yard",type: "Body",
resource:[{name: "Iron",qty: 5,z:null},{name: "Wood",qty: 1,z:null}]},
{name: "Random Uncommon Resource",silver: 50,time: "4h",building: "Alchemists' Guild",upgrade: "Wisdom",pic: "Uncommon Boon.jpg",
resource:[{name: "Wildfire",qty: 1,qual: "Rare",z:null},{name: "Rashers of Bacon",qty: 1,z:null},{name: "Fish",qty: 5,z:null}]},
{name: "Harrier",silver: 60,time: "3h",building: "Stables",upgrade: "Stalls",pic: "Hooded Horseman.jpg",
resource:[{name: "Militia",qty: 1,z:null},{name: "Horse",qty: 1,z:null},{name: "Grains",qty: 5,z:null}]},
{name: "Heavy Crossbow",silver: 200,time: "6h",building: "Watchtower",upgrade: "Third Story",
resource:[{name: "Light Crossbow",qty: 1,z:null},{name: "Wood",qty: 7,z:null},{name: "Cloth",qty: 5,z:null}]},
{name: "Heavy Knight",silver: 450,time: "12h",building: "Tourney Arena",upgrade: "Herald",quality: "Rare",type: "Unit",pic: "Lancer.jpg",special: "+4% to all attacks and defense",
resource:[{name: "Lancer",qty: 1,qual: "Rare",pic: "Lancer.jpg",z:null},{name: "Gold Torc",qty: 1,qual: "Uncommon",z:null},{name: "Metal Shield",qty: 1,qual: "Uncommon",pic: "Hefty Shield.jpg",z:null}]},
{name: "Heavy Warhammer",silver: 2500,time: "1d4h",building: "Feast",upgrade: "Goblets",
resource:[{name: "Warhammer",qty: 3,qual: "Rare",z:null},{name: "Lead",qty: 25,qual: "Uncommon",z:null},{name: "Steel",qty: 5,qual: "Uncommon",z:null}]},
{name: "Hefty Broadsword",silver: 800,time: "15h",building: "Smithy",upgrade: "Hammer and Tongs",
resource:[{name: "Broadsword",qty: 2,qual: "Uncommon",z:null},{name: "Steel",qty: 9,qual: "Uncommon",z:null},{name: "Hard Wood",qty: 5,qual: "Uncommon",z:null}]},
{name: "Heirloom Necklace",silver: 2500,time: "1d 4h",building: "Fishery",upgrade: "Poles",quality: "legendary",
resource:[{name: "Moonstone Necklace",qty: 3,qual: "rare",z:null},{name: "Precious Ore",qty: 15,qual: "uncommon",z:null},{name: "Lead",qty: 15,qual: "uncommon",z:null}]},
{name: "Horse Archer",silver: 450,time: "12h",building: "Reliquary",
resource:[{name: "Horseman",qty: 2,z:null},{name: "Composite Bow",qty: 2,qual: "Uncommon",z:null}]},
{name: "Horseman",silver: 60,time: "3h",building: "Reliquary",type: "Unit",
resource:[{name: "Smallfolk",qty: 3,z:null},{name: "Horse",qty: 3,z:null},{name: "Cloth",qty: 3,z:null}]},
{name: "Hunter",silver: 200,time: "6h",building: "Hunting Lodge",quality: "Uncommon",
resource:[{name: "Tracker",qty: 1,z:null},{name: "Shortbow",qty: 1,z:null},{name: "Woven Belt",qty: 1,qual: "Uncommon",z:null}]},
{name: "Illustrious Mercer",silver: 20000,time: "12h",building: "Artisan Quarters",upgrade: "Loom",
resource:[{name: "Master Mercer",qty: 1,qual: "Legendary",pic: "Deluxe Fancy Man.jpg",z:null},{name: "Dark Diamond Ring",qty: 2,qual: "rare",z:null},{name: "Grand Pewter Chain",qty: 4,qual: "Legendary",pic: "Silver Chain.jpg",z:null}]},
{name: "Incense",silver: 20,time: "1h 20m",building: "R'hllor Temple",upgrade: "Servants Rooms",
resource:[{name: "Black Ash",qty: 1,z:null},{name: "Pure Water",qty: 1,z:null},{name: "Fine Wood",qty: 1,qual: "Uncommon",z:null}]},
{name: "Jason's Reforged Sword",silver: 25000,time: "18h",building: "Godswood",upgrade: "",
resource:[{name: "Remnants of Jason's Sword",qty: 1,qual: "Legendary",pic: "Jason Sword Remnants.jpg",z:null},{name: "Masterwork Greatsword",qty: 1,qual: "Legendary",z:null},{name: "Valyrian Glyphs",qty: 5,qual: "Rare",z:null}]},
{name: "Jerkin",silver: 200,time: "6h",building: "Holdfast",upgrade: "Earthworks",quality: "Uncommon",
resource:[{name: "Doublet",qty: 2,z:null},{name: "Cloth",qty: 3,z:null},{name: "Fur",qty: 3,z:null}]},
{name: "Jeweled Armor",silver: 2500,time: "1d 4h",building: "Mine",upgrade: "Workers Tools",quality: "Legendary",
resource:[{name: "Forest Armor",qty: 2,qual: "Rare",z:null},{name: "Sparkling Jewel",qty: 10,qual: "Rare",z:null},{name: "Steel",qty: 15,qual: "Uncommon",z:null}]},
{name: "Jeweler",silver: 200,time: "6h",building: "Mine",quality: "Uncommon",pic: "Emissary.jpg",
resource:[{name: "Trader",qty: 1,z:null},{name: "Iron",qty: 8,z:null},{name: "Ore",qty: 10,z:null}]},
{name: "Ladder",silver: 60,time: "3h",building: "Siege Works",upgrade: "Ladder Fabrication",
resource:[{name: "Wood",qty: 2,z:null},{name: "Smallfolk",qty: 2,z:null},{name: "Fish",qty: 2,z:null}]},
{name: "Lancer",silver: 450,time: "12h",building: "Tourney Arena",upgrade: "Lances",quality: "Rare",type: "Unit",
resource:[{name: "Mounted Knight",qty: 1,qual: "Rare",z:null},{name: "Pike",qty: 1,qual: "Uncommon",z:null},{name: "Silk Garment",qty: 1,qual: "Uncommon",z:null}]},
{name: "Leather Armor",silver: 60,time: "3h",building: "Holdfast",
resource:[{name: "Doublet",qty: 1,z:null},{name: "Fur",qty: 1,z:null},{name: "Cloth",qty: 1,z:null}]},
{name: "Leather Belt",silver: 60,time: "3h",building: "Shanty",
resource:[{name: "Cloth",qty: 2,z:null},{name: "Fur",qty: 4,z:null}]},
{name: "Leather-bound Book",silver: 60,time: "3h",building: "Market",upgrade: "Cloth Stall",
resource:[{name: "Cloth",qty: 2,z:null},{name: "Fur",qty: 2,z:null},{name: "Ore",qty: 1,z:null}]},
{name: "Ledger Book",silver: 450,time: "12h",building: "Fishery",upgrade: "Drying Racks",quality: "Rare",
resource:[{name: "Vellum Scroll",qty: 2,qual: "Uncommon",z:null},{name: "Leather-bound Book",qty: 2,z:null},{name: "Cloth",qty: 2,z:null}]},
{name: "Light Crossbow",silver: 60,time: "3h",building: "Watchtower",
resource:[{name: "Wood",qty: 3,z:null},{name: "Cloth",qty: 2,z:null},{name: "Fur",qty: 1,z:null}]},
{name: "Linen Clothing",silver: 60,time: "3h",building: "Embassy",
resource:[{name: "Cloth",qty: 4,z:null},{name: "Fur",qty: 2,z:null}]},
{name: "Lockbox",silver: 200,time: "6h",building: "Treasury",upgrade: "Crown and Scepter",
resource:[{name: "Purse",qty: 1,z:null},{name: "Ore",qty: 6,z:null}]},
{name: "Longbow",silver: 450,time: "12h",building: "Hunting Lodge",upgrade: "Falconry Mews",quality: "Rare",
resource:[{name: "Composite Bow",qty: 2,qual: "Uncommon",z:null},{name: "Wood",qty: 10,z:null},{name: "Cloth",qty: 4,z:null}]},
{name: "Longsword",silver: 60,time: "3h",building: "Smithy",type: "Hand",
resource:[{name: "Shortsword",qty: 1,pic: "Short Sword.jpg",z:null},{name: "Iron",qty: 2,z:null}]},
{name: "Madam",silver: 2500,time: "1d 4h",building: "Shanty",upgrade: "Pit Fires",quality: "Legendary",
resource:[{name: "Courtesan",qty: 3,qual: "Rare",z:null},{name: "Dyed Textile",qty: 15,qual: "Uncommon",z:null},{name: "Precious Ore",qty: 15,qual: "Uncommon",z:null}]},
{name: "Manacles",silver: 200,time: "6h",building: "Siege Works",quality: "Uncommon",
resource:[{name: "Lead",qty: 2,qual: "Uncommon",z:null},{name: "Iron",qty: 6,z:null},{name: "Ore",qty: 6,z:null}]},
{name: "Mangonel",silver: 450,time: "12h",building: "Siege Works",upgrade: "Mangonel",
resource:[{name: "Catapult",qty: 2,qual: "Uncommon",z:null},{name: "Stone",qty: 10,z:null},{name: "Fish",qty: 4,z:null}]},
{name: "Mark of the Little Birds",silver: 500,time: "5h",building: "R'hllor Temple",
resource:[{name: "Agent's Sign",qty: 2,pic: "Agent's Sign Seal.jpg",z:null},{name: "Saboteur's Sign",qty: 2,pic: "Saboteur's Sign Seal.jpg",z:null},{name: "Cutpurses's Sign",qty: 2,pic: "Cutpurses's Sign Seal.jpg",z:null}]},
{name: "Master Assassin",silver: 20000,time: "12h",building: "Watchtower",upgrade: "Archery Platforms",quality: "Peerless",
resource:[{name: "Guild Assassin",qty: 1,qual: "Legendary",z:null},{name: "Expert Crossbowman",qty: 2,qual: "Rare",z:null},{name: "Grand Tailored Tunic",qty: 4,qual: "Legendary",pic: "Unremarkable Tunic.jpg",z:null}]},
{name: "Master Crafted Cuirass",silver: 20000,time: "12h",building: "Shipyard",upgrade: "Coils of Rope",
resource:[{name: "Grand Cuirass",qty: 1,qual: "Legendary",z:null},{name: "Masterwork Splint Mail",qty: 2,qual: "rare",z:null},{name: "Grand Short Hauberk",qty: 4,qual: "Legendary",pic: "Chainmail.jpg",z:null}]},
{name: "Master Crafted Longbow",silver: 20000,time: "12h",building: "Hunting Lodge",upgrade: "Falconry Mews",
resource:[{name: "Taut Longbow",qty: 1,qual: "Legendary",z:null},{name: "Taut Composite Bow",qty: 2,qual: "rare",z:null},{name: "Grand Mistwood Dagger",qty: 4,qual: "Legendary",pic: "Dagger.jpg",z:null}]},
{name: "Master Crafted Warhammer",silver: 20000,time: "12h",building: "Feast",upgrade: "Goblets",
resource:[{name: "Heavy Warhammer",qty: 1,qual: "Legendary",z:null},{name: "Grand Shield",qty: 2,qual: "rare",z:null},{name: "Grand Hardened Mace",qty: 4,qual: "Legendary",pic: "Mace.jpg",z:null}]},
{name: "Master Furrier",silver: 2500,time: "1d 4h",building: "Artisan Quarters",upgrade: "Jewelry",quality: "Legendary",
resource:[{name: "Furrier",qty: 3,qual: "Rare",z:null},{name: "Lead",qty: 20,qual: "Uncommon",z:null},{name: "Precious Ore",qty: 10,qual: "Uncommon",z:null}]},
{name: "Master Ledger Book",silver: 2500,time: "1d 4h",building: "Fishery",upgrade: "Drying Racks",quality: "Legendary",
resource:[{name: "Ledger Book",qty: 3,qual: "Rare",z:null},{name: "Fine Wood",qty: 17,qual: "uncommon",z:null},{name: "Dyed Textile",qty: 13,qual: "Uncommon",z:null}]},
{name: "Master Mercer",silver: 2500,time: "1d 4h",building: "Artisan Quarters",upgrade: "Loom",quality: "legendary",
resource:[{name: "Mercer",qty: 3,qual: "rare",z:null},{name: "Dyed Textile",qty: 20,qual: "uncommon",z:null},{name: "Precious Ore",qty: 10,qual: "uncommon",z:null}]},
{name: "Master Spicer",silver: 2500,time: "1d 4h",building: "Artisan Quarters",upgrade: "Pottery",quality: "legendary",
resource:[{name: "Spicer",qty: 3,qual: "rare",z:null},{name: "Fine Wood",qty: 20,qual: "uncommon",z:null},{name: "Precious Ore",qty: 10,qual: "uncommon",z:null}]},
{name: "Masterwork Greatsword",silver: 2500,time: "1d 14h",building: "Smithy",upgrade: "Weapon Rack",
resource:[{name: "Hefty Broadsword",qty: 3,qual: "Rare",z:null},{name: "Steel",qty: 11,qual: "Uncommon",z:null},{name: "Hard Wood",qty: 7,qual: "Uncommon",z:null}]},
{name: "Masterwork Spear",silver: 2500,time: "1d 4h",building: "Glasshouse",upgrade: "Topiary",
resource:[{name: "Spear",qty: 3,qual: "Rare",z:null},{name: "Steel",qty: 12,qual: "Uncommon",z:null},{name: "Hard Wood",qty: 18,qual: "Uncommon",z:null}]},
{name: "Masterwork Splint Mail",silver: 800,time: "15h",building: "Holdfast",upgrade: "Arrowslits",quality: "Rare",
resource:[{name: "Splint Mail",qty: 2,qual: "Uncommmon",z:null},{name: "Steel",qty: 9,qual: "Uncommon",z:null},{name: "Dyed Textile",qty: 5,qual: "Uncommon",z:null}]},
{name: "Mead",silver: 10,time: "1h",building: "Godswood",type: "Drink",
resource:[{name: "Grains",qty: 3,z:null},{name: "Wood",qty: 1,z:null},{name: "Stone",qty: 1,z:null}]},
{name: "Mercer",silver: 450,time: "12h",building: "Artisan Quarters",upgrade: "Loom",quality: "rare",
resource:[{name: "Merchant",qty: 6,z:null},{name: "Cloth",qty: 8,z:null},{name: "Ore",qty: 4,z:null}]},
{name: "Merchant (Unit)",silver: 60,time: "3h",building: "Market",
resource:[{name: "Trader",qty: 1,z:null},{name: "Leather-bound Book",qty: 1,z:null},{name: "Silver Chain",qty: 1,z:null}]},
{name: "Shield Bearers",silver: 200,time: "6h",building: "Armory",upgrade: "Quenching Trough",quality: "Uncommon",type: "Unit",special: "+3% to Battle defense",
resource:[{name: "Militia",qty: 2,z:null},{name: "Metal Shield",qty: 2,qual: "Uncommon",pic: "Hefty Shield.jpg",z:null},{name: "",qty: 1,z:null}]},
{name: "Militia",silver: 0,
resource:[]},
{name: "Milk of the Poppy",silver: 60,time: "3h",building: "Embassy",
resource:[{name: "Grains",qty: 4,z:null},{name: "Fish",qty: 2,z:null}]},
{name: "Milk of the Poppy",silver: 60,time: "3h",building: "Embassy",
resource:[{name: "Grains",qty: 4,z:null},{name: "Fish",qty: 2,z:null}]},
{name: "Moleskin Gloves",silver: 200,time: "6h",building: "Shanty",upgrade: "Village Watch",
resource:[{name: "Fingerless Gloves",qty: 1,z:null},{name: "Fur",qty: 6,z:null},{name: "Cloth",qty: 6,z:null}]},
{name: "Moonstone Bracelet",silver: 450,time: "12h",building: "Glasshouse",upgrade: "Orangery",
resource:[{name: "Gold Bracelet",qty: 2,qual: "Uncommon",z:null},{name: "Ore",qty: 8,z:null},{name: "Fur",qty: 6,z:null}]},
{name: "Moonstone Brooch",silver: 450,time: "12h",building: "Feast",upgrade: "Flagons of Drink",quality: "Rare",
resource:[{name: "Silver Brooch",qty: 4,z:null},{name: "Silver Chain",qty: 3,z:null},{name: "Ore",qty: 8,z:null}]},
{name: "Moonstone Necklace",silver: 450,time: "12h",building: "Fishery",upgrade: "Poles",
resource:[{name: "Gold Necklace",qty: 2,qual: "uncommon",z:null},{name: "Silver Chain",qty: 1,qual: "rare",z:null},{name: "Ore",qty: 8,z:null}]},
{name: "Moonstone Torc",silver: 450,time: "12h",building: "Mine",upgrade: "Molds",quality: "Rare",
resource:[{name: "Gold Torc",qty: 2,qual: "Uncommon",z:null},{name: "Ore",qty: 10,z:null},{name: "Cloth",qty: 4,z:null}]},
{name: "Mounted Escort",silver: 800,time: "15h",building: "Stables",upgrade: "Stalls",
resource:[{name: "Harrier",qty: 3,pic: "Hooded Horseman.jpg",z:null},{name: "Scout",qty: 3,pic: "Hooded Horseman.jpg",z:null},{name: "Fine Wood",qty: 14,qual: "Uncommon",z:null}]},
{name: "Mounted Knight",silver: 450,time: "12h",building: "Tourney Arena",upgrade: "Viewing Box",quality: "Rare",
resource:[{name: "Armored Knight",qty: 1,qual: "Rare",z:null},{name: "Warhorse",qty: 1,z:null},{name: "Purse",qty: 1,z:null}]},
{name: "Mummer",silver: 200,time: "6h",building: "Feast",quality: "Uncommon",
resource:[{name: "Fool",qty: 2,z:null},{name: "Wood",qty: 7,z:null},{name: "Cloth",qty: 7,z:null}]},
{name: "Net",silver: 200,time: "6h",building: "Fishery",upgrade: "Nets",quality: "Uncommon",
resource:[{name: "Cloth",qty: 8,z:null},{name: "Stone",qty: 6,z:null},{name: "Iron",qty: 4,z:null}]},
{name: "Nettle Poultice",silver: 50,time: "3h",building: "R'hllor Temple",type: "Medicine",
resource:[{name: "Grains",qty: 4,z:null},{name: "Fish",qty: 3,z:null},{name: "Cloth",qty: 2,z:null}]},
{name: "Nightshade",silver: 800,time: "15h",building: "Embassy",upgrade: "Fortified Gate",quality: "Rare",
resource:[{name: "Dreamwine",qty: 2,qual: "Uncommon",z:null},{name: "Dyed Textile",qty: 7,qual: "Uncommon",z:null},{name: "Fine Wood",qty: 7,qual: "Uncommon",z:null}]},
{name: "Nobleman's Coat",silver: 20000,time: "12h",building: "Glasshouse",upgrade: "Reflecting Pool",
resource:[{name: "Filigreed Outfit",qty: 1,qual: "Legendary",z:null},{name: "Delicate Silk Garment",qty: 2,qual: "rare",z:null},{name: "Grand Embroidered Raiment",qty: 4,qual: "Legendary",pic: "Embroidered Tunic.jpg",z:null}]},
{name: "Nocturnal Assassin",silver: 2500,time: "12h",building: "Embassy",
resource:[{name: "Hunter of the Night",qty: 1,qual: "Legendary",pic: "Nocturnal Hunter.jpg",z:null},{name: "Dirk",qty: 3,z:null},{name: "Shadowbinder Mask",qty: 1,qual: "Rare",z:null}]},
{name: "Nocturnal Deceiver",silver: 2500,time: "12h",building: "Market",
resource:[{name: "Hunter of the Night",qty: 1,qual: "Legendary",pic: "Nocturnal Hunter.jpg",z:null},{name: "Parchment Scroll",qty: 3,z:null},{name: "Shadowbinder Mask",qty: 1,qual: "Rare",z:null}]},
{name: "Nocturnal Killer",silver: 2500,time: "12h",building: "Smithy",
resource:[{name: "Hunter of the Night",qty: 1,qual: "Legendary",pic: "Nocturnal Hunter.jpg",z:null},{name: "Shortbow",qty: 3,z:null},{name: "Shadowbinder Mask",qty: 1,qual: "Rare",z:null}]},
{name: "Offering",silver: 2500,time: "1d 4h",building: "R'hllor Temple",upgrade: "Asshai Prophecy Books",quality: "Legendary",
resource:[{name: "Ceremonial Bowl",qty: 3,qual: "Uncommon",z:null},{name: "Ceremonial Dagger",qty: 2,qual: "Rare",z:null},{name: "Sacrifice",qty: 9,qual: "Rare",z:null}]},
{name: "Oracle",silver: 450,time: "12h",building: "R'hllor Temple",upgrade: "Statue of Azor Ahai",quality: "Rare",
resource:[{name: "Red Priest",qty: 1,qual: "Uncommon",z:null},{name: "Woods Witch",qty: 1,qual: "Uncommon",z:null},{name: "Septa",qty: 1,qual: "Uncommon",z:null}]},
{name: "Ostler",silver: 60,time: "3h",building: "Stables",type: "Unit",
resource:[{name: "Smallfolk",qty: 1,z:null},{name: "Fur",qty: 2,z:null},{name: "Grains",qty: 3,z:null}]},
{name: "Parade Mummer",silver: 800,time: "15h",building: "Feast",upgrade: "Candelabra",quality: "Legendary",
resource:[{name: "Mummer",qty: 2,qual: "Uncommon",z:null},{name: "Dyed Textile",qty: 8,qual: "Uncommon",z:null},{name: "Lead",qty: 6,qual: "Uncommon",z:null}]},
{name: "Parchment Scroll",silver: 60,time: "3h",building: "Warehouse",
resource:[{name: "Leather-bound Book",qty: 1,z:null},{name: "Cloth",qty: 1,z:null},{name: "Fur",qty: 1,z:null}]},
{name: "Partisan",silver: 800,time: "15h",building: "Practice Yard",upgrade: "Practice Dummies",
resource:[{name: "Pike",qty: 2,qual: "Uncommon",z:null},{name: "Steel",qty: 5,qual: "Uncommon",z:null},{name: "Hard Wood",qty: 9,qual: "Uncommon",z:null}]},
{name: "Peddler",silver: 60,time: "3h",building: "Stables",upgrade: "Stalls",type: "Unit",pic: "Trader.jpg",
resource:[{name: "Trader",qty: 1,z:null},{name: "Horse",qty: 1,z:null},{name: "Grains",qty: 5,z:null}]},
{name: "Phalanx",silver: 450,time: "12h",building: "Armory",upgrade: "Tower Shields",
resource:[{name: "Shield Bearers",qty: 2,qual: "Uncommon",z:null},{name: "Pikeman",qty: 2,qual: "Uncommon",z:null},{name: "Halfhelm",qty: 4,z:null}]},
{name: "Phalanx Commander",silver: 20000,time: "12h",building: "Armory",upgrade: "Tower Shields",
resource:[{name: "Elite Phalanx",qty: 1,qual: "Legendary",z:null},{name: "Grand Breastplate",qty: 2,qual: "rare",z:null},{name: "Grand Short Hauberk",qty: 4,qual: "Legendary",pic: "Chainmail.jpg",z:null}]},
{name: "Pike",silver: 200,time: "6h",building: "Armory",upgrade: "Forge",
resource:[{name: "Longsword",qty: 2,z:null},{name: "Wood",qty: 4,z:null},{name: "Iron",qty: 2,z:null}]},
{name: "Pikeman",silver: 200,time: "6h",building: "Holdfast",upgrade: "Pikes",quality: "Uncommon",type: "Unit",
resource:[{name: "Militia",qty: 1,z:null},{name: "Pike",qty: 1,qual: "Uncommon",z:null}]},
{name: "Pocketed Belt",silver: 450,time: "12h",building: "Feast",upgrade: "Candelabra",quality: "Rare",
resource:[{name: "Woven Belt",qty: 2,qual: "Uncommon",z:null},{name: "Cloth",qty: 12,z:null},{name: "Fur",qty: 2,z:null}]},
{name: "Poisoned Cask",silver: 450,time: "12h",building: "Arbor",upgrade: "Flasks",
resource:[{name: "Blindeye",qty: 2,qual: "Uncommon",z:null},{name: "Wood",qty: 8,z:null},{name: "Iron",qty: 6,z:null}]},
{name: "Poisoned Ring",silver: 450,time: "12h",building: "Shipyard",upgrade: "Dry Dock",quality: "Rare",
resource:[{name: "Dreamwine",qty: 1,qual: "Uncommon",z:null},{name: "Blindeye",qty: 1,z:null},{name: "Gold Ring",qty: 3,z:null}]},
{name: "Pure Water",silver: 5,time: "30m",building: "Alchemists' Guild",upgrade: "Acolyte",
resource:[{name: "Black Ash",qty: 1,z:null},{name: "Mead",qty: 1,z:null},{name: "Cloth",qty: 3,z:null}]},
{name: "Purse",silver: 60,time: "3h",building: "Artisan Quarters",
resource:[{name: "Gold Ring",qty: 1,z:null},{name: "Ore",qty: 2,z:null}]},
{name: "Pyre",silver: 8000,time: "9h",building: "R'hllor Temple",upgrade: "Blazing Firepit",quality: "rare",type: "none",
resource:[{name: "Hard Wood",qty: 3,qual: "Uncommon",z:null},{name: "Fine Wood",qty: 3,qual: "Uncommon",z:null},{name: "Wildfire",qty: 1,qual: "Rare",z:null}]},
{name: "Ram",silver: 200,time: "6h",building: "Siege Works",upgrade: "Ram Fabrication",quality: "Uncommon",special: "+1% Battle actions",
resource:[{name: "Turtle",qty: 1,z:null},{name: "Iron",qty: 6,z:null},{name: "Horse",qty: 6,z:null}]},
{name: "Reaving Ship",silver: 450,time: "12h",building: "Shipyard",upgrade: "Slip",
resource:[{name: "Ship",qty: 1,qual: "Rare",z:null},{name: "Sailor",qty: 3,z:null},{name: "Composite Bow",qty: 2,qual: "Uncommon",z:null}]},
{name: "Receipt",silver: 450,time: "12h",building: "Reliquary",upgrade: "Dragon Skull",
resource:[{name: "Bill of Sale",qty: 2,qual: "Uncommon",z:null},{name: "Horse",qty: 6,z:null},{name: "Cloth",qty: 8,z:null}]},
{name: "Red Gem",silver: 30,time: "1h",building: "Mine",
resource:[{name: "Ore",qty: 10,z:null},{name: "Stone",qty: 5,z:null}]},
{name: "Red Priest",silver: 200,time: "6h",building: "R'hllor Temple",upgrade: "Tattoo Room",quality: "Uncommon",
resource:[{name: "Red Robe",qty: 2,z:null},{name: "Smallfolk",qty: 2,z:null},{name: "Grains",qty: 4,z:null}]},
{name: "Red Robe",silver: 60,time: "3h",building: "R'hllor Temple",upgrade: "Fiery Heart Banner",
resource:[{name: "Cloth",qty: 3,z:null},{name: "Ore",qty: 1,z:null},{name: "Grains",qty: 2,z:null}]},
{name: "Roughspun Cloak",silver: 60,time: "3h",building: "Workshop",pic: "Roughspun_Cloak.jpg",
resource:[{name: "Cloth",qty: 4,z:null},{name: "Fur",qty: 2,z:null}]},
{name: "Saboteur",silver: 200,time: "6h",building: "Workshop",
resource:[{name: "Eavesdropper",qty: 1,pic: "Hooded Figure.jpg",z:null},{name: "Satin Cloak",qty: 1,qual: "Uncommon",pic: "Satin_Cloak.jpg",z:null}]},
{name: "Sailor",silver: 60,time: "3h",building: "Shipyard",
resource:[{name: "Smallfolk",qty: 1,z:null},{name: "Dagger",qty: 1,z:null},{name: "Gold Ring",qty: 1,z:null}]},
{name: "Satin Cloak",silver: 200,time: "6h",building: "Workshop",upgrade: "Suspicious Cart",quality: "Uncommon",
resource:[{name: "Roughspun Cloak",qty: 1,z:null},{name: "Cloth",qty: 4,z:null},{name: "Fur",qty: 8,z:null}]},
{name: "Scale Armor",silver: 60,time: "3h",building: "Holdfast",type: "Body",special: "+1% to [[Fight]] defense",
resource:[{name: "Doublet",qty: 1,z:null},{name: "Iron",qty: 2,z:null}]},
{name: "Scorpion",silver: 200,time: "6h",building: "Siege Works",upgrade: "Scorpion Fabrication",quality: "Uncommon",special: "+1% Intrigue actions",
resource:[{name: "Cloth",qty: 6,z:null},{name: "Wood",qty: 6,z:null},{name: "Grains",qty: 6,z:null}]},
{name: "Scout",silver: 60,time: "3h",building: "Stables",upgrade: "Stalls",pic: "Hooded Horseman.jpg",
resource:[{name: "Eavesdropper",qty: 1,pic: "Hooded Figure.jpg",z:null},{name: "Horse",qty: 1,z:null},{name: "Grains",qty: 5,z:null}]},
{name: "Seal of the Dragon",silver: 5500,time: "15h",building: "Reliquary",
resource:[{name: "Mark of the Little Birds",qty: 3,qual: "Uncommon",pic: "Mark of the Little Birds Seal.jpg",z:null},{name: "Agent's Sign",qty: 3,pic: "Agent's Sign Seal.jpg",z:null},{name: "Cutpurses's Sign",qty: 3,pic: "Cutpurses's Sign Seal.jpg",z:null}]},
{name: "Seal of the Fish",silver: 5500,time: "15h",building: "Fishery",quality: "Rare",type: "Seal",pic: "Seal of the Fish Seal.jpg",
resource:[{name: "Treasurer's Imprint",qty: 3,qual: "Uncommon",pic: "Treasurers Imprint Seal.jpg",z:null},{name: "Merchant's Mark",qty: 3,pic: "Merchant's Mark Seal.jpg",z:null},{name: "Fraud's Imprint",qty: 3,pic: "Fraud's Imprint Seal.jpg",z:null}]},
{name: "Seal of the Kraken",silver: 5500,time: "15h",building: "Shipyard",
resource:[{name: "Warrior's Imprint",qty: 3,qual: "Uncommon",pic: "Warrior's Imprint Seal.jpg",link: "Warrior's Imprint",z:null},{name: "Blacksmith's Mark",qty: 3,pic: "Blacksmith's Mark Seal.jpg",z:null},{name: "Raider's Notch",qty: 3,pic: "Raider's Notch Seal.jpg",z:null}]},
{name: "Seal of the Lion",silver: 5500,time: "15h",building: "Mine",
resource:[{name: "Treasurer's Imprint",qty: 3,qual: "Uncommon",pic: "Treasurers Imprint Seal.jpg",z:null},{name: "Fraud's Imprint",qty: 3,pic: "Fraud's Imprint Seal.jpg",z:null},{name: "Bailiff's Mark",qty: 3,pic: "Bailiff's Mark Seal.jpg",z:null}]},
{name: "Seal of the Rose",silver: 5500,time: "15h",building: "Arbor",
resource:[{name: "Treasurer's Imprint",qty: 3,qual: "Uncommon",pic: "Treasurers Imprint Seal.jpg",link: "Treasurer's Imprint",z:null},{name: "Merchant's Mark",qty: 3,pic: "Merchant's Mark Seal.jpg",z:null},{name: "Bailiff's Mark",qty: 3,pic: "Bailiff's Mark Seal.jpg",z:null}]},
{name: "Seal of the Stag",silver: 5500,time: "15h",building: "Feast",upgrade: "",
resource:[{name: "Warrior's Imprint",qty: 3,qual: "Uncommon",pic: "Warrior's Imprint Seal.jpg",link: "Warrior's Imprint",z:null},{name: "Blacksmith's Mark",qty: 3,pic: "Blacksmith's Mark Seal.jpg",z:null},{name: "Symbol of Help",qty: 3,pic: "Symbol of Help Seal.jpg",z:null}]},
{name: "Seal of the Sun and Spear",silver: 5500,time: "15h",building: "Glasshouse",upgrade: "",
resource:[{name: "Mark of the Little Birds",qty: 3,qual: "Uncommon",pic: "Mark of the Little Birds Seal.jpg",z:null},{name: "Agent's Sign",qty: 3,pic: "Agent's Sign Seal.jpg",z:null},{name: "Saboteur's Sign",qty: 3,pic: "Saboteur's Sign Seal.jpg",z:null}]},
{name: "Seal of the Wolf",silver: 5500,time: "15h",building: "Hunting Lodge",upgrade: "",
resource:[{name: "Warrior's Imprint",qty: 3,qual: "Uncommon",pic: "Warrior's Imprint Seal.jpg",link: "Warrior's Imprint",z:null},{name: "Raider's Notch",qty: 3,qual: "Common",pic: "Raider's Notch Seal.jpg",link: "Raider's Notch",z:null},{name: "Symbol of Help",qty: 3,qual: "Common",pic: "Symbol of Help Seal.jpg",link: "Symbol of Help",z:null}]},
{name: "Secure Lockbox",silver: 800,time: "15h",building: "Treasury",upgrade: "Crown and Scepter",
resource:[{name: "Lockbox",qty: 2,qual: "Uncommon",z:null},{name: "Steel",qty: 5,qual: "Uncommon",z:null},{name: "Precious Ore",qty: 9,qual: "Uncommon",z:null}]},
{name: "Seer",silver: 60,time: "3h",building: "Godswood",upgrade: "Heart Tree",type: "Unit",pic: "Female Peasant.jpg",
resource:[{name: "Smallfolk",qty: 1,z:null},{name: "Fish",qty: 5,z:null},{name: "Leather-bound Book",qty: 1,z:null}]},
{name: "Septa",silver: 200,time: "6h",building: "Sept",upgrade: "Altar to the Mother",quality: "Uncommon",
resource:[{name: "Devout",qty: 1,pic: "Female Peasant.jpg",z:null},{name: "Wood Shield",qty: 1,z:null},{name: "Silver Brooch",qty: 1,z:null}]},
{name: "Shadowbinder Mask",silver: 800,time: "12h",building: "R'hllor Temple",upgrade: "Blazing Firepit",quality: "Rare",
resource:[{name: "Dyed Textile",qty: 8,qual: "Uncommon",z:null},{name: "Precious Ore",qty: 5,qual: "Uncommon",z:null},{name: "Red Priest",qty: 2,qual: "Uncommon",z:null}]},
{name: "Shield Bearers",silver: 200,time: "6h",building: "Armory",
resource:[{name: "Militia",qty: 2,z:null},{name: "Metal Shield",qty: 2,qual: "Uncommon",pic: "Hefty Shield.jpg",z:null}]},
{name: "Ship",silver: 450,time: "12h",building: "Shipyard",quality: "Rare",
resource:[{name: "Wood",qty: 10,z:null},{name: "Cloth",qty: 5,z:null},{name: "Sailor",qty: 3,z:null}]},
{name: "Shortbow",silver: 60,time: "3h",building: "Practice Yard",
resource:[{name: "Wood",qty: 3,z:null},{name: "Cloth",qty: 2,z:null},{name: "Fur",qty: 1,z:null}]},
{name: "Shortsword",silver: 60,time: "3h",building: "Smithy",
resource:[{name: "Wood",qty: 2,z:null},{name: "Iron",qty: 2,z:null}]},
{name: "Siege Tower",silver: 450,time: "12h",building: "Siege Works",upgrade: "Siege Tower",
resource:[{name: "Ram",qty: 1,qual: "Uncommon",z:null},{name: "Ladder",qty: 1,z:null},{name: "Smallfolk",qty: 14,z:null}]},
{name: "Silk Garment",silver: 200,time: "6h",building: "Embassy",upgrade: "Balcony",quality: "Uncommon",
resource:[{name: "Linen Clothing",qty: 1,z:null},{name: "Cloth",qty: 8,z:null},{name: "Fur",qty: 4,z:null}]},
{name: "Silk Gloves",silver: 450,time: "12h",building: "Mine",upgrade: "Workers Tools",quality: "Rare",
resource:[{name: "Moleskin Gloves",qty: 2,qual: "Uncommon",z:null},{name: "Cloth",qty: 9,z:null},{name: "Fur",qty: 5,z:null}]},
{name: "Silver Bracelet",silver: 60,time: "3h",building: "Artisan Quarters",
resource:[{name: "Silver Brooch",qty: 1,z:null},{name: "Ore",qty: 1,z:null},{name: "Cloth",qty: 1,z:null}]},
{name: "Silver Brooch",silver: 60,time: "3h",building: "Market",upgrade: "Ore Stall",
resource:[{name: "Ore",qty: 4,z:null},{name: "Cloth",qty: 1,z:null}]},
{name: "Silver Chain",silver: 60,time: "3h",building: "Market",upgrade: "Fish Stall",
resource:[{name: "Ore",qty: 3,z:null},{name: "Fur",qty: 1,z:null},{name: "Cloth",qty: 1,z:null}]},
{name: "Silver Necklace",silver: 60,time: "3h",building: "Warehouse",
resource:[{name: "Silver Chain",qty: 1,z:null},{name: "Ore",qty: 2,z:null}]},
{name: "Silver Torc",silver: 60,time: "3h",building: "Artisan Quarters",
resource:[{name: "Silver Chain",qty: 1,z:null},{name: "Ore",qty: 1,z:null},{name: "Fur",qty: 1,z:null}]},
{name: "Smuggling Vessel",silver: 450,time: "12h",building: "Alchemists' Guild",upgrade: "Acolyte",quality: "rare",
resource:[{name: "Wood",qty: 17,z:null},{name: "Cloth",qty: 9,z:null},{name: "Thief",qty: 4,pic: "Hooded Figure.jpg",z:null}]},
{name: "Snow Bear Skull Helm",silver: 1500,time: "6h",building: "Godswood",quality: "Rare",type: "Body",
resource:[{name: "Black Bear Skull Helm",qty: 1,qual: "uncommon",pic: "Bear Skull Helm.jpg",z:null},{name: "Cold Armor",qty: 4,qual: "uncommon",pic: "Splint Mail.jpg",z:null},{name: "Ore",qty: 16,z:null}]},
{name: "Sparkling Jewel",silver: 15,time: "2h",building: "Alchemists' Guild",upgrade: "Transmutation Chamber",quality: "Rare",
resource:[{name: "Black Ash",qty: 6,z:null},{name: "Precious Ore",qty: 6,qual: "Uncommon",z:null},{name: "Ore",qty: 6,z:null}]},
{name: "Spear",silver: 450,time: "12h",building: "Glasshouse",
resource:[{name: "Axe",qty: 2,qual: "Uncommon",z:null},{name: "Wood",qty: 8,z:null},{name: "Iron",qty: 6,z:null}]},
{name: "Spearman",silver: 450,time: "12h",building: "Glasshouse",upgrade: "Orangery",quality: "rare",
resource:[{name: "Militia",qty: 1,z:null},{name: "Spear",qty: 1,qual: "Rare",z:null},{name: "iron",qty: 3,z:null}]},
{name: "Spell-Forged Longsword",silver: 750,time: "3h",building: "Godswood",quality: "Rare",type: "Hand",
resource:[{name: "Spell-Forged Blade",qty: 1,qual: "Rare",z:null},{name: "Longsword",qty: 3,z:null},{name: "Iron",qty: 8,z:null}]},
{name: "Spicer",silver: 450,time: "12h",building: "Artisan Quarters",upgrade: "Pottery",quality: "Rare",
resource:[{name: "Merchant",qty: 6,z:null},{name: "Grains",qty: 8,z:null},{name: "Ore",qty: 4,z:null}]},
{name: "Spitfire",silver: 450,time: "12h",building: "Siege Works",upgrade: "Spitfire",
resource:[{name: "Scorpion",qty: 2,qual: "Uncommon",z:null},{name: "Cloth",qty: 7,z:null},{name: "Ore",qty: 7,z:null}]},
{name: "Splint Mail",silver: 200,time: "6h",building: "Holdfast",upgrade: "Arrowslits",quality: "Uncommon",type: "Body",special: "+3% to [[Fight]] defense",
resource:[{name: "Scale Armor",qty: 2,z:null},{name: "Iron",qty: 4,z:null},{name: "Cloth",qty: 2,z:null}]},
{name: "Standard Carrier",silver: 60,time: "3h",building: "Arbor",pic: "Phalanx.jpg",
resource:[{name: "Militia",qty: 1,z:null},{name: "Eavesdropper",qty: 1,pic: "Hooded Figure.jpg",z:null},{name: "Trader",qty: 1,z:null}]},
{name: "Steel-Shod Warhorse",silver: 800,time: "15h",building: "Stables",upgrade: "War Horse",quality: "Rare",type: "Unit",
resource:[{name: "Warhorse",qty: 2,z:null},{name: "Ostler",qty: 1,z:null},{name: "Steel",qty: 4,qual: "Uncommon",z:null}]},
{name: "Surcoat",silver: 450,time: "12h",building: "Shipyard",upgrade: "Coils of Rope",quality: "Rare",
resource:[{name: "Jerkin",qty: 2,qual: "Uncommon",z:null},{name: "Cloth",qty: 7,z:null},{name: "Fur",qty: 7,z:null}]},
{name: "Sweetsleep",silver: 450,time: "12h",building: "Mine",upgrade: "Tailings",quality: "Rare",
resource:[{name: "Dreamwine",qty: 2,qual: "Uncommon",z:null},{name: "Grains",qty: 11,z:null},{name: "Fish",qty: 3,z:null}]},
{name: "Taut Composite Bow",silver: 800,time: "15h",building: "Practice Yard",upgrade: "Archery Butts",quality: "Rare",type: "Hand",
resource:[{name: "Composite Bow",qty: 2,qual: "Uncommon",z:null},{name: "Hard Wood",qty: 8,qual: "Uncommon",z:null},{name: "Fine Wood",qty: 6,qual: "Uncommon",z:null}]},
{name: "Taut Longbow",silver: 2500,time: "1d 4h",building: "Hunting Lodge",upgrade: "Falconry Mews",quality: "Legendary",
resource:[{name: "Longbow",qty: 3,qual: "Rare",z:null},{name: "Hard Wood",qty: 15,qual: "Uncommon",z:null},{name: "Fine Wood",qty: 15,qual: "Uncommon",z:null}]},
{name: "Thief",silver: 60,time: "3h",building: "Shanty",
resource:[{name: "Eavesdropper",qty: 1,pic: "Hooded Figure.jpg",z:null},{name: "Grains",qty: 5,z:null},{name: "Fur",qty: 3,z:null}]},
{name: "Tools Cart",silver: 450,time: "12h",building: "Workshop",upgrade: "Infernal Device",quality: "Rare",
resource:[{name: "Cart",qty: 1,pic: "Cart of Tools.jpg",z:null},{name: "Dirk",qty: 3,z:null},{name: "Blindeye",qty: 3,qual: "Uncommon",z:null}]},
{name: "Tracker",silver: 60,time: "3h",building: "Hunting Lodge",
resource:[{name: "Smallfolk",qty: 1,z:null},{name: "Fur",qty: 7,z:null}]},
{name: "Trader",silver: 60,time: "3h",building: "Market",
resource:[{name: "Smallfolk",qty: 1,z:null}]},
{name: "Treasurer's Imprint",silver: 500,time: "5h",building: "Sept",
resource:[{name: "Merchant's Mark",qty: 2,pic: "Merchant's Mark Seal.jpg",z:null},{name: "Fraud's Imprint",qty: 2,pic: "Fraud's Imprint Seal.jpg",z:null},{name: "Bailiff's Mark",qty: 2,pic: "Bailiff's Mark Seal.jpg",z:null}]},
{name: "Trebuchet",silver: 60,time: "3h",building: "Siege Works",upgrade: "Trebuchet Fabrication",
resource:[{name: "Stone",qty: 2,z:null},{name: "Ore",qty: 2,z:null},{name: "Cloth",qty: 2,z:null}]},
{name: "Turtle",silver: 60,time: "3h",building: "Siege Works",upgrade: "Turtle",
resource:[{name: "Fur",qty: 2,z:null},{name: "Horse",qty: 2,z:null},{name: "Grains",qty: 2,z:null}]},
{name: "Undetectable Poison",silver: 2500,time: "1d 4h",building: "Arbor",upgrade: "Flasks",
resource:[{name: "Poisoned Cask",qty: 3,qual: "Rare",z:null},{name: "Fine Wood",qty: 15,qual: "Uncommon",z:null},{name: "Hard Wood",qty: 15,qual: "Uncommon",z:null}]},
{name: "Unremarkable Tunic",silver: 60,time: "3h",building: "Watchtower",
resource:[{name: "Cloth",qty: 3,z:null},{name: "Fur",qty: 3,z:null}]},
{name: "Valuable Prisoner",silver: 450,time: "12h",building: "Siege Works",quality: "Rare",
resource:[{name: "Manacles",qty: 1,qual: "Uncommon",z:null},{name: "Saboteur",qty: 2,qual: "Uncommon",z:null},{name: "Smallfolk",qty: 12,z:null}]},
{name: "Chance of Valyrian Steel Arakh",silver: 6000,time: "12h",building: "Godswood",quality: "Chance",pic: "Valyrian Steel Arakh.jpg",
resource:[{name: "Valyrian Steel Bastard Sword",qty: 1,qual: "legendary",z:null},{name: "Dragon Barding Caparison Fragment",qty: 8,qual: "rare",z:null},{name: "Dragon Armor Tail Fragment",qty: 3,qual: "rare",z:null}]},
{name: "Valyrian Steel Bastard Sword",silver: 3000,time: "9h",building: "Godswood",quality: "Legendary",type: "Hand",
resource:[{name: "Valyrian Steel Longsword",qty: 1,qual: "Legendary",z:null},{name: "Broadsword",qty: 5,qual: "uncommon",z:null},{name: "Steel",qty: 5,qual: "uncommon",z:null}]},
{name: "Chance of Valyrian Steel Curved Dagger",silver: 6000,time: "12h",building: "Godswood",quality: "Chance",pic: "Valyrian Steel Curved Dagger.jpg",
resource:[{name: "Valyrian Steel Bastard Sword",qty: 1,qual: "legendary",z:null},{name: "Dragon Armor Leather Strap",qty: 8,qual: "rare",z:null},{name: "Dragon Armor Tail Fragment",qty: 3,qual: "rare",z:null}]},
{name: "Chance of Valyrian Steel Dragon Horn",silver: 6000,time: "12h",building: "Godswood",quality: "Chance",pic: "Valyrian Steel Dragon Horn.jpg",
resource:[{name: "Valyrian Steel Bastard Sword",qty: 1,qual: "legendary",z:null},{name: "Dragon Armor Body Fragment",qty: 8,qual: "rare",z:null},{name: "Dragon Armor Tail Fragment",qty: 3,qual: "rare",z:null}]},
{name: "Valyrian Steel Longsword",silver: 1500,time: "6h",building: "Godswood",quality: "Rare",type: "Hand",
resource:[{name: "Spell-Forged Longsword",qty: 1,qual: "Rare",z:null},{name: "Longsword",qty: 6,qual: "uncommon",z:null},{name: "Iron",qty: 16,z:null}]},
{name: "Vellum Scroll",silver: 200,time: "6h",building: "Treasury",upgrade: "Crown and Scepter",
resource:[{name: "Parchment Scroll",qty: 1,z:null},{name: "Leather-bound Book",qty: 1,z:null},{name: "Cloth",qty: 6,z:null}]},
{name: "Wagon",silver: 60,time: "3h",building: "Warehouse",upgrade: "Crates",
resource:[{name: "Cart",qty: 1,pic: "Cart of Tools.jpg",z:null},{name: "Horse",qty: 1,z:null},{name: "Fish",qty: 6,z:null}]},
{name: "Warhammer",silver: 450,time: "12h",building: "Feast",upgrade: "Goblets",quality: "Rare",
resource:[{name: "Broadsword",qty: 2,z:null},{name: "Iron",qty: 8,z:null},{name: "Wood",qty: 6,z:null}]},
{name: "Warhorse",silver: 60,time: "3h",building: "Stables",upgrade: "War Horse",type: "Unit",
resource:[{name: "Horse",qty: 1,z:null},{name: "Ostler",qty: 1,z:null},{name: "Leather Armor",qty: 1,z:null}]},
{name: "Warm Fur-Lined Cloak",silver: 2500,time: "1d 4h",building: "Hunting Lodge",upgrade: "Cleaning and Skinning Station",quality: "Legendary",
resource:[{name: "Fur-trimmed Cloak",qty: 3,qual: "Rare",z:null},{name: "Dyed Textile",qty: 20,qual: "Uncommon",z:null},{name: "Precious Ore",qty: 10,qual: "Uncommon",z:null}]},
{name: "Warrior's Imprint",silver: 500,time: "5h",building: "Godswood",
resource:[{name: "Blacksmith's Mark",qty: 2,pic: "Blacksmith's Mark Seal.jpg",z:null},{name: "Raider's Notch",qty: 2,pic: "Raider's Notch Seal.jpg",z:null},{name: "Symbol of Help",qty: 2,pic: "Symbol of Help Seal.jpg",z:null}]},
{name: "Water Dancer Blade",silver: 1500,time: "6h",building: "Godswood",
resource:[{name: "Bravo's Blade",qty: 1,qual: "uncommon",pic: "Bravos Blade.jpg",z:null},{name: "Parrying Blade",qty: 4,qual: "Uncommon",pic: "Dirk.jpg",z:null},{name: "Iron",qty: 16,z:null}]},
{name: "Widow's Blood",silver: 800,time: "15h",building: "Workshop",upgrade: "Signal Lantern",quality: "Rare",pic: "Dreamwine.jpg",
resource:[{name: "Blindeye",qty: 2,qual: "Uncommon",z:null},{name: "Lead",qty: 7,qual: "Uncommon",z:null},{name: "Dyed Textile",qty: 7,qual: "Uncommon",z:null}]},
{name: "Wildfire",silver: 30,time: "2h",building: "Alchemists' Guild",upgrade: "Fresh Wildfire",special: "Small chance of producing Wildfire",
resource:[{name: "Pure Water",qty: 2,z:null},{name: "Flickering Fire",qty: 2,pic: "Pyre.jpg",z:null},{name: "Stone",qty: 4,z:null}]},
{name: "Wolfsbane",silver: 800,time: "15h",building: "Shanty",upgrade: "Pit Fires",
resource:[{name: "Blindeye",qty: 1,qual: "Uncommon",z:null},{name: "Dreamwine",qty: 1,qual: "Uncommon",z:null},{name: "Fine Wood",qty: 14,qual: "Uncommon",z:null}]},
{name: "Wood Shield",silver: 60,time: "3h",building: "Armory",upgrade: "Round Shield",
resource:[{name: "Wood",qty: 5,z:null},{name: "Iron",qty: 1,z:null}]},
{name: "Woods Witch",silver: 200,time: "6h",building: "Godswood",upgrade: "Heart Tree Leaves",quality: "Uncommon",
resource:[{name: "Seer",qty: 1,pic: "Female Peasant.jpg",z:null},{name: "Milk of the Poppy",qty: 1,z:null},{name: "Dagger",qty: 1,z:null}]},
{name: "Woven Belt",silver: 200,time: "6h",building: "Shanty",upgrade: "Drainage Sewers",quality: "Uncommon",
resource:[{name: "Leather Belt",qty: 1,z:null},{name: "Cloth",qty: 10,z:null},{name: "Fur",qty: 2,z:null}]}
];
